apiVersion: apps/v1
kind: Deployment
metadata:
  name: scp
  namespace: vplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scp
  template:
    metadata:
      labels:
        app: scp
    spec:
      containers:
        - name: scp
          image: docker.io/vinch05/scp:v2.7.5
          imagePullPolicy: IfNotPresent
          command: ['open5gs-scpd', '-c', '/etc/open5gs/scp.yaml']
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/scp.yaml
              subPath: scp.yaml
          ports:
            - containerPort: 80
              name: http
      volumes:
        - name: config
          configMap:
            name: scp-config
