apiVersion: apps/v1
kind: Deployment
metadata:
  name: scp
  namespace: vplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scp
  template:
    metadata:
      labels:
        app: scp
    spec:
      containers:
        - name: scp
          image: $(REGISTRY_URL)/scp:v2.7.5
          imagePullPolicy: Never
          command: [ "open5gs-scpd", "-c", "/etc/open5gs/scp.yaml" ]
          env:
            - name: REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: registry-config
                  key: REGISTRY_URL
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/scp.yaml
              subPath: scp.yaml
          ports:
            - containerPort: 80
              name: http
      volumes:
        - name: config
          configMap:
            name: scp-config