apiVersion: v1
kind: Service
metadata:
  name: networkui
  namespace: hplmn
spec:
  selector:
    app: networkui
  ports:
    - protocol: TCP
      port: 9998
      targetPort: http
      nodePort: 30998
  type: NodePort
