apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-config
  namespace: vplmn
data:
  udm.yaml: |
    logger:
      file:
        path: /var/log/open5gs/udm.log
      level: debug
    global:

    udm:
      sbi:
        server:
          - dev: eth0
            advertise: udm.5gc.mnc070.mcc999.3gppnetwork.org
        client:
          nrf:
            - uri: http://nrf.5gc.mnc070.mcc999.3gppnetwork.org