apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-config
  namespace: hplmn
data:
  udr.yaml: |
    db_uri: mongodb://mongodb.hplmn.svc.cluster.local/open5gs

    logger:
      file:
        path: /var/log/open5gs/udr.log

    global:

    udr:
      sbi:
        server:
          - dev: eth0
            advertise: udr.5gc.mnc001.mcc001.3gppnetwork.org
        client:
          nrf:
            - uri: http://nrf.5gc.mnc001.mcc001.3gppnetwork.org
