apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
  namespace: hplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      labels:
        app: udr
    spec:
      containers:
        - name: udr
          image: docker.io/library/udr-local:v2.7.5
          imagePullPolicy: IfNotPresent
          command: [ "open5gs-udrd", "-c", "/etc/open5gs/udr.yaml" ]
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/udr.yaml
              subPath: udr.yaml
          ports:
            - containerPort: 80
              name: http
      volumes:
        - name: config
          configMap:
            name: udr-config