apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
  namespace: hplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      labels:
        app: udr
    spec:
      containers:
        - name: udr
          image: docker.io/vinch05/udr:v2.7.5
          imagePullPolicy: IfNotPresent
          command: ['open5gs-udrd', '-c', '/etc/open5gs/udr.yaml']
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/udr.yaml
              subPath: udr.yaml
          ports:
            - containerPort: 80
              name: http
      volumes:
        - name: config
          configMap:
            name: udr-config
