apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-config
  namespace: hplmn
data:
  ausf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/ausf.log
      level: debug

    global:

    ausf:
      sbi:
        server:
          - dev: eth0
            advertise: ausf.5gc.mnc001.mcc001.3gppnetwork.org
        client:
          nrf:
            - uri: http://nrf.5gc.mnc001.mcc001.3gppnetwork.org