apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
  namespace: hplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
    spec:
      containers:
        - name: ausf
          image: docker.io/vinch05/ausf:v2.7.5
          imagePullPolicy: IfNotPresent
          command: ["open5gs-ausfd", "-c", "/etc/open5gs/ausf.yaml"]
          volumeMounts:
          - name: config
            mountPath: /etc/open5gs/ausf.yaml
            subPath: ausf.yaml
          ports:
            - containerPort: 80
              name: sbi
      volumes:
      - name: config
        configMap:
          name: ausf-config
