apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
  namespace: hplmn
data:
  nrf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/nrf.log

    global:

    nrf:
      serving:
        - plmn_id:
            mcc: 001
            mnc: 01
      sbi:
        server:
          - dev: eth0
            advertise: nrf.5gc.mnc001.mcc001.3gppnetwork.org
            port: 80