apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf
  namespace: hplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
    spec:
      containers:
        - name: nrf
          image: docker.io/vinch05/nrf:v2.7.5
          imagePullPolicy: IfNotPresent
          command: ['open5gs-nrfd', '-c', '/etc/open5gs/nrf.yaml']
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/nrf.yaml
              subPath: nrf.yaml
          ports:
            - containerPort: 80
              name: http
      volumes:
        - name: config
          configMap:
            name: nrf-config
