apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-config
  namespace: hplmn
data:
  udm.yaml: |
    logger:
      file:
        path: /var/log/open5gs/udm.log
      level: debug
      
    global:
      max:
        ue: 100000

    udm:
      sbi:
        server:
          - dev: eth0
            advertise: udm.5gc.mnc001.mcc001.3gppnetwork.org
        client:
          nrf:
            - uri: http://nrf.5gc.mnc001.mcc001.3gppnetwork.org