apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  namespace: hplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      labels:
        app: udm
    spec:
      containers:
        - name: udm
          image: docker.io/vinch05/udm:v2.7.5
          imagePullPolicy: IfNotPresent
          command: ['open5gs-udmd', '-c', '/etc/open5gs/udm.yaml']
          resources:
            requests:
              cpu: '5m'
              memory: '512Mi'
            limits:
              cpu: '10m'
              memory: '5Gi'
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/udm.yaml
              subPath: udm.yaml
          ports:
            - containerPort: 80
              name: sbi
      volumes:
        - name: config
          configMap:
            name: udm-config
