apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  namespace: hplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      labels:
        app: udm
    spec:
      containers:
        - name: udm
          image: docker.io/library/udm-local:v2.7.5
          imagePullPolicy: IfNotPresent
          command: [ "open5gs-udmd", "-c", "/etc/open5gs/udm.yaml" ]
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/udm.yaml
              subPath: udm.yaml
          ports:
            - containerPort: 80
              name: http
      volumes:
        - name: config
          configMap:
            name: udm-config