apiVersion: v1
kind: PersistentVolume
metadata:
  name: sepp-pcap-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/sepp-pcap
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sepp-pcap-pvc
  namespace: vplmn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
