apiVersion: v1
kind: Service
metadata:
  name: sepp
  namespace: vplmn
spec:
  selector:
    app: sepp
  ports:
    - name: sbi
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sepp-n32c
  namespace: vplmn
spec:
  selector:
    app: sepp
  ports:
    - name: n32c
      protocol: TCP
      port: 7778
      targetPort: 7778
---
apiVersion: v1
kind: Service
metadata:
  name: sepp-n32f
  namespace: vplmn
spec:
  selector:
    app: sepp
  ports:
    - name: n32f
      protocol: TCP
      port: 7779
      targetPort: 7779