apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: hplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: docker.io/vinch05/webui:v2.7.5
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URI
              value: 'mongodb://mongodb.hplmn.svc.cluster.local:27017/open5gs'
            - name: HOSTNAME
              value: '0.0.0.0'
            - name: PORT
              value: '9999'
            - name: NODE_ENV
              value: 'dev'
          ports:
            - containerPort: 9999
              name: http
