apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
  namespace: vplmn
data:
  nrf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/nrf.log

    global:
      max:
        ue: 100000

    nrf:
      serving:
        - plmn_id:
            mcc: 999
            mnc: 70
      sbi:
        server:
          - dev: eth0
            advertise: nrf.5gc.mnc070.mcc999.3gppnetwork.org
            port: 80