apiVersion: v1
kind: ConfigMap
metadata:
  name: h-sepp-config
data:
  sepp.yaml: |
    logger:
      file:
        path: /var/log/open5gs/sepp.log
    global:
      max:
        ue: 1024
    sepp:
      default:
        tls:
          server:
            private_key: /etc/open5gs/tls/sepp1.key
            cert: /etc/open5gs/tls/sepp1.chain.crt
          client:
            cacert: /etc/open5gs/tls/ca-bundle.crt
            verify: true
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
        client:
          nrf:
            - uri: http://h-nrf.default.svc.cluster.local:80
      n32:
        server:
          - sender: sepp1.localdomain
            scheme: https
            address: 0.0.0.0
            port: 7778
            n32f:
              scheme: https
              address: 0.0.0.0
              port: 7779
        client:
          sepp:
            - receiver: sepp2.localdomain
              uri: https://v-sepp.default.svc.cluster.local:7778
              verify_client: true
              n32f:
                uri: https://v-sepp.default.svc.cluster.local:7779
                verify_client: true
