apiVersion: v1
kind: ConfigMap
metadata:
  name: h-udm-config
data:
  udm.yaml: |
    logger:
      file:
        path: /var/log/open5gs/udm.log

    global:

    udm:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
        client:
          nrf:
            - uri: http://h-nrf.default.svc.cluster.local:80
