apiVersion: v1
kind: ConfigMap
metadata:
  name: h-udr-config
data:
  udr.yaml: |
    db_uri: mongodb://mongodb.default.svc.cluster.local/open5gs

    logger:
      file:
        path: /var/log/open5gs/udr.log

    global:

    udr:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
        client:
          nrf:
            - uri: http://h-nrf.default.svc.cluster.local:80
