db_uri: mongodb://db.open5gs.org/open5gs

logger:
  file:
    path: /var/log/open5gs/udr.log

global:

udr:
  sbi:
    server:
    - address: udr.5gc.mnc001.mcc001.3gppnetwork.org
      port: 80
    client:
      scp:
      - uri: http://scp.5gc.mnc001.mcc001.3gppnetwork.org:80
