gnodeb:
  controlif:
    ip: 'gnb.packetrusher.org'
    port: 38412
  dataif:
    ip: 'gnb.packetrusher.org'
    port: 2152
  plmnlist:
    mcc: '999'
    mnc: '70'
    tac: '000001'
    gnbid: '000008'
  slicesupportlist:
    sst: '01'
    sd: '000001'


ue:
  hplmn:
    mcc: '999'
    mnc: '70'
  msin: '1234567891'
  key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
  opc: 'E8ED289DEBA952E4283B54E88E6183CA'
  dnn: 'internet'
  snssai:
    sst: 01
    sd: '000001'
  amf: '8000'
  sqn: '00000000'
  routingindicator: '0000'
  protectionScheme: 0
  integrity:
    nia0: false
    nia1: false
    nia2: true
    nia3: false
  ciphering:
    nea0: true
    nea1: false
    nea2: true
    nea3: false

amfif:
  - ip: 'amf.5gc.mnc070.mcc999.3gppnetwork.org'
    port: 38412
logs:
  level: 4



