# TShark Configuration for Open5GS Network Capture
capture:
  interface: br-ogs
  output: /captures/network_traffic.pcap
  rotate: true
  rotate_interval: 3600 # Rotate files every hour
  max_files: 24 # Keep last 24 hours of captures
  max_size: 100 # Maximum file size in MB before rotation

# Capture filters (using BPF syntax)
filters:
  # 5G core network protocols - using port-based filters for BPF
  - 'port 36412 or port 38412 or port 8805 or port 2152 or port 2123 or port 3868 or port 8080'
  # Add more specific filters as needed
  # - "net 10.33.33.0/24"  # Filter for Open5GS network
  # - "port 7777 or port 7778 or port 7779"  # SEPP ports

# Display filters (for real-time analysis)
display_filters:
  - 'ngap or http2 or pfcp or diameter or gtp'

# Logging configuration
logging:
  level: info
  file: /var/log/tshark.log
  max_size: 10 # MB
  backups: 5

# Performance settings
performance:
  buffer_size: 100 # MB
  max_packets: 1000000
  promiscuous_mode: false # Note: in tshark, -p actually turns promiscuous mode OFF
