logger:
  file:
    path: /var/log/open5gs/amf.log

global:

amf:
  sbi:
    server:
      - address: amf.5gc.mnc070.mcc999.3gppnetwork.org
        port: 80
    client:
      scp:
        - uri: http://scp.5gc.mnc070.mcc999.3gppnetwork.org:80
  ngap:
    server:
      - address: amf.5gc.mnc070.mcc999.3gppnetwork.org
  access_control:
    - plmn_id:
        mcc: 999
        mnc: 70
    - plmn_id:
        mcc: 001
        mnc: 01
  guami:
    - plmn_id:
        mcc: 999
        mnc: 70
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 999
        mnc: 70
      tac: 1
  plmn_support:
    - plmn_id:
        mcc: 999
        mnc: 70
      s_nssai:
        - sst: 1
          sd: 000001
  security:
    integrity_order: [NIA2, NIA1, NIA0]
    ciphering_order: [NEA0, NEA1, NEA2]
  network_name:
    full: Open5GS
  amf_name: open5gs-amf0
  time:
    t3512:
      value: 540
