logger:
  file:
    path: /var/log/open5gs/ausf.log

global:

ausf:
  sbi:
    server:
      - address: ausf.5gc.mnc070.mcc999.3gppnetwork.org
        port: 80
    client:
      scp:
        - uri: http://scp.5gc.mnc070.mcc999.3gppnetwork.org:80
