logger:
  file:
    path: /var/log/open5gs/nssf.log

global:

nssf:
  sbi:
    server:
    - address: nssf.5gc.mnc070.mcc999.3gppnetwork.org
      port: 80
    client:
      scp:
        - uri: http://scp.5gc.mnc070.mcc999.3gppnetwork.org:80
      nsi:
      - uri: http://nrf.5gc.mnc070.mcc999.3gppnetwork.org:80
        s_nssai:
          sst: 1
          sd: 1
