logger:
  file:
    path: /var/log/open5gs/scp.log

global:

scp:
  sbi:
    server:
    - address: scp.5gc.mnc070.mcc999.3gppnetwork.org
      port: 80
    client:
      nrf:
      - uri: http://nrf.5gc.mnc070.mcc999.3gppnetwork.org:80
