logger:
  file:
    path: /var/log/open5gs/sepp.log

global:

sepp:
  default:
    tls:
      server:
        schema: https
        private_key: /etc/open5gs/tls/server.key
        cert: /etc/open5gs/tls/server.crt
        verify_client: true
        ca_cert: /etc/open5gs/tls/ca.crt
      client:
        schema: https
        client_private_key: /etc/open5gs/tls/client.key
        client_cert: /etc/open5gs/tls/client.crt
        ca_cert: /etc/open5gs/tls/trusted-ca-bundle.crt
  sbi:
    server:
      - address: sepp.5gc.mnc070.mcc999.3gppnetwork.org
        port: 443
        tls:
          enabled: true
    client:
      nrf:
        - uri: http://nrf.5gc.mnc070.mcc999.3gppnetwork.org:80
  n32:
    server:
      - sender: sepp.5gc.mnc070.mcc999.3gppnetwork.org
        tls:
          enabled: true
          verify_client: true
    client:
      sepp:
        - receiver: sepp.5gc.mnc001.mcc001.3gppnetwork.org
          uri: https://sepp.5gc.mnc001.mcc001.3gppnetwork.org:443
          tls:
            enabled: true
            verify_server: true
