logger:
  file:
    path: /var/log/open5gs/upf.log

global:

upf:
  pfcp:
    server:
      - address: upf.5gc.mnc070.mcc999.3gppnetwork.org
    client:
  gtpu:
    server:
      - address: upf.5gc.mnc070.mcc999.3gppnetwork.org
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
