apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-config
  namespace: vplmn
data:
  ausf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/ausf.log
      level: debug

    global:
      max:
        ue: 100000

    ausf:
      sbi:
        server:
          - dev: eth0
            advertise: ausf.5gc.mnc070.mcc999.3gppnetwork.org
        client:
          nrf:
            - uri: http://nrf.5gc.mnc070.mcc999.3gppnetwork.org