apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
  namespace: vplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
    spec:
      containers:
        - name: ausf
          image: docker.io/vinch05/ausf:v2.7.5
          imagePullPolicy: IfNotPresent
          command: ['open5gs-ausfd', '-c', '/etc/open5gs/ausf.yaml']
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/ausf.yaml
              subPath: ausf.yaml
          ports:
            - containerPort: 80
              name: sbi
      volumes:
        - name: config
          configMap:
            name: ausf-config
