apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-config
  namespace: vplmn
data:
  smf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/smf.log

    global:
      max:
        ue: 100000

    smf:
      sbi:
        server:
          - dev: eth0
            advertise: smf.5gc.mnc070.mcc999.3gppnetwork.org
        client:
          nrf:
            - uri: http://nrf.5gc.mnc070.mcc999.3gppnetwork.org
      pfcp:
        server:
          - dev: eth0
            advertise: smf.5gc.mnc070.mcc999.3gppnetwork.org
        client:
          upf:
            - address: upf.5gc.mnc070.mcc999.3gppnetwork.org
      gtpu:
        server:
          - dev: eth0
            advertise: smf.5gc.mnc070.mcc999.3gppnetwork.org
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dnn: internet
      dns:
        - 8.8.8.8
        - 8.8.4.4
      mtu: 1400 