apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
  namespace: vplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
        - name: smf
          image: docker.io/vinch05/smf:v2.7.5
          imagePullPolicy: IfNotPresent
          command: ['open5gs-smfd', '-c', '/etc/open5gs/smf.yaml']
          resources:
            requests:
              cpu: '5m'
              memory: '512Mi'
            limits:
              cpu: '10m'
              memory: '5Gi'
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/smf.yaml
              subPath: smf.yaml
          ports:
            - containerPort: 80
              name: sbi
            - containerPort: 8805
              name: pfcp
      volumes:
        - name: config
          configMap:
            name: smf-config
