apiVersion: v1
kind: Service
metadata:
  name: smf
  namespace: vplmn
spec:
  selector:
    app: smf
  ports:
    - name: sbi
      protocol: TCP
      port: 80
      targetPort: sbi 
    - name: pfcp
      protocol: UDP
      port: 8805
      targetPort: pfcp