apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: ghcr.io/borjis131/webui:v2.7.5
        env:
        - name: DB_URI
          value: "mongodb://mongodb/open5gs"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: PORT
          value: "9999"
        - name: NODE_ENV
          value: "dev"
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  selector:
    app: webui
  ports:
  - port: 9999
    targetPort: 9999
  type: NodePort
  nodePort: 30999
