apiVersion: v1
kind: ConfigMap
metadata:
  name: v-ausf-config
data:
  ausf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/ausf.log

    global:

    ausf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
        client:
          nrf:
            - uri: http://v-nrf.default.svc.cluster.local:80
