apiVersion: v1
kind: ConfigMap
metadata:
  name: v-bsf-config
data:
  bsf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/bsf.log

    global:

    bsf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
        client:
          nrf:
            - uri: http://v-nrf.default.svc.cluster.local:80
