apiVersion: v1
kind: ConfigMap
metadata:
  name: v-nrf-config
data:
  nrf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/nrf.log

    global:

    nrf:
      serving:
        - plmn_id:
            mcc: 999
            mnc: 70
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
