apiVersion: v1
kind: ConfigMap
metadata:
  name: v-nssf-config
data:
  nssf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/nssf.log

    global:

    nssf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
        client:
          nrf:
            - uri: http://v-nrf.default.svc.cluster.local:80
          nsi:
            - uri: http://v-nrf.default.svc.cluster.local:80
              s_nssai:
                sst: 1
                sd: 000001
