apiVersion: v1
kind: ConfigMap
metadata:
  name: v-smf-config
data:
  smf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/smf.log

    global:

    smf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
        client:
          nrf:
            - uri: http://v-nrf.default.svc.cluster.local:80
      pfcp:
        server:
          - address: 0.0.0.0
        client:
          upf:
            - address: v-upf.default.svc.cluster.local
      gtpu:
        server:
          - address: 0.0.0.0
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dnn: internet
          plmn_id:
            mcc: 999
            mnc: 70
        - subnet: 10.46.0.0/16
          gateway: 10.46.0.1
          dnn: internet
          plmn_id:
            mcc: 001
            mnc: 01
      dns:
        - 8.8.8.8
        - 8.8.4.4
      mtu: 1400
