apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
  namespace: vplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      labels:
        app: udr
    spec:
      containers:
        - name: udr
          image: docker.io/vinch05/udr:v2.7.5
          imagePullPolicy: IfNotPresent
          command: ['open5gs-udrd', '-c', '/etc/open5gs/udr.yaml']
          resources:
            requests:
              cpu: '5m'
              memory: '512Mi'
            limits:
              cpu: '10m'
              memory: '5Gi'
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/udr.yaml
              subPath: udr.yaml
          ports:
            - containerPort: 80
              name: sbi
      volumes:
        - name: config
          configMap:
            name: udr-config
