apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-config
  namespace: vplmn
data:
  amf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/amf.log
      level: debug

    global:

    amf:
      sbi:
        server:
          - dev: eth0
            advertise: amf.5gc.mnc070.mcc999.3gppnetwork.org
        client:
          scp:
            - uri: http://scp.5gc.mnc070.mcc999.3gppnetwork.org
      ngap:
        server:
          - dev: eth0
      access_control:
        - plmn_id:
            mcc: 999
            mnc: 70
        - plmn_id:
            mcc: 001
            mnc: 01
      guami:
        - plmn_id:
            mcc: 999
            mnc: 70
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: 999
            mnc: 70
          tac: 1
        - plmn_id:
            mcc: 001
            mnc: 01
          tac: 1
      plmn_support:
        - plmn_id:
            mcc: 999
            mnc: 70
          s_nssai:
            - sst: 1
        - plmn_id:
            mcc: 001
            mnc: 01
          s_nssai:
            - sst: 1
      security:
        integrity_order: [ NIA2, NIA0, NIA1 ]
        ciphering_order: [ NEA0, NEA2, NEA1 ]
      network_name:
        full: Open5GS
      amf_name: open5gs-amf0
      time:
        t3512:
          value: 540