apiVersion: v1
kind: Service
metadata:
  name: amf
  namespace: vplmn
spec:
  type: NodePort
  selector:
    app: amf
  ports:
    - name: sbi
      port: 80
      targetPort: 80
      protocol: TCP
    - name: ngap
      port: 38412
      targetPort: 38412
      protocol: SCTP
      nodePort: 31412