services:
  tshark:
    container_name: tshark
    image: 'nicolaka/netshoot'
    command: >
      sh -c "mkdir -p /captures &&
             chmod 777 /captures &&
             echo 'Starting packet capture...' &&
             # Capture all traffic on br-ogs interface
             tshark -i br-ogs -w /captures/open5gs_all.pcap -P &
             # Specific protocol captures
             tshark -i br-ogs -f 'port 7777 or port 8777' -w /captures/sepp_sbi.pcap -P &
             tshark -i br-ogs -f 'port 7778 or port 7779 or port 8778 or port 8779' -w /captures/n32_interfaces.pcap -P &
             tshark -i br-ogs -f 'sctp' -w /captures/n1_n2_interfaces.pcap -P &
             tshark -i br-ogs -f 'udp port 2152' -w /captures/n3_interface.pcap -P &&
             echo 'Packet capture started successfully' &&
             tail -f /dev/null"
    network_mode: 'host'
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./captures:/captures
    restart: unless-stopped

  db:
    container_name: db
    image: 'mongo:${MONGODB_VERSION}'
    command: 'mongod --bind_ip 0.0.0.0 --port 27017'
    networks:
      open5gs:
        aliases:
          - db.open5gs.org
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    ports:
      - '0.0.0.0:27017:27017/tcp'
    depends_on:
      - tshark

  h-nrf:
    container_name: h-nrf
    image: 'nrf:${OPEN5GS_VERSION}'
    build:
      context: ../../images/nrf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/nrf.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.10
        aliases:
          - nrf.5gc.mnc001.mcc001.3gppnetwork.org
    configs:
      - source: h-nrf_config
        target: /etc/open5gs/custom/nrf.yaml
    depends_on:
      - tshark

  h-ausf:
    container_name: h-ausf
    image: 'ausf:${OPEN5GS_VERSION}'
    build:
      context: ../../images/ausf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/ausf.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.11
        aliases:
          - ausf.5gc.mnc001.mcc001.3gppnetwork.org
    configs:
      - source: h-ausf_config
        target: /etc/open5gs/custom/ausf.yaml
    depends_on:
      - h-nrf
      - h-scp

  h-udm:
    container_name: h-udm
    image: 'udm:${OPEN5GS_VERSION}'
    build:
      context: ../../images/udm
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/udm.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.12
        aliases:
          - udm.5gc.mnc001.mcc001.3gppnetwork.org
    configs:
      - source: h-udm_config
        target: /etc/open5gs/custom/udm.yaml
    depends_on:
      - h-nrf
      - h-scp

  h-udr:
    container_name: h-udr
    image: 'udr:${OPEN5GS_VERSION}'
    build:
      context: ../../images/udr
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/udr.yaml'
    restart: unless-stopped
    networks:
      open5gs:
        ipv4_address: 10.33.33.13
        aliases:
          - udr.5gc.mnc001.mcc001.3gppnetwork.org
    configs:
      - source: h-udr_config
        target: /etc/open5gs/custom/udr.yaml
    depends_on:
      - db
      - h-nrf
      - h-scp
  h-scp:
    container_name: h-scp
    image: 'scp:${OPEN5GS_VERSION}'
    build:
      context: ../../images/scp
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/scp.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.14
        aliases:
          - scp.5gc.mnc001.mcc001.3gppnetwork.org
    configs:
      - source: h-scp_config
        target: /etc/open5gs/custom/scp.yaml
    cap_add:
      - NET_ADMIN

  h-sepp:
    container_name: h-sepp
    image: 'sepp:${OPEN5GS_VERSION}'
    build:
      context: ../../images/sepp
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/default/sepp.yaml'
    restart: unless-stopped
    networks:
      open5gs:
        ipv4_address: 10.33.33.20
        aliases:
          - sepp.5gc.mnc001.mcc001.3gppnetwork.org
          - sepp1.localdomain
    environment:
      - SEPP_TYPE=sepp1
      - REGENERATE_CERTS=true
      - TLS_DIR=/etc/open5gs/default/tls
      - SEPP_FQDN=sepp1.localdomain
      - SEPP_PLMN_FQDN=sepp.5gc.mnc001.mcc001.3gppnetwork.org
    volumes:
      - sepp_certs:/etc/open5gs/default/tls
      - sepp_ca:/etc/open5gs/default/ca
    configs:
      - source: h-sepp_config
        target: /etc/open5gs/default/sepp.yaml
    ports:
      - '0.0.0.0:7777:7777/tcp' # SBI Server
      - '0.0.0.0:7778:7778/tcp' # N32c Server
      - '0.0.0.0:7779:7779/tcp' # N32f Server
    depends_on:
      - h-nrf
      - h-scp

  v-nrf:
    container_name: v-nrf
    image: 'nrf:${OPEN5GS_VERSION}'
    build:
      context: ../../images/nrf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/nrf.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.30
        aliases:
          - nrf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-nrf_config
        target: /etc/open5gs/custom/nrf.yaml

  v-ausf:
    container_name: v-ausf
    image: 'ausf:${OPEN5GS_VERSION}'
    build:
      context: ../../images/ausf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/ausf.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.31
        aliases:
          - ausf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-ausf_config
        target: /etc/open5gs/custom/ausf.yaml
    depends_on:
      - v-nrf
      - h-scp

  v-nssf:
    container_name: v-nssf
    image: 'nssf:${OPEN5GS_VERSION}'
    build:
      context: ../../images/nssf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/nssf.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.32
        aliases:
          - nssf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-nssf_config
        target: /etc/open5gs/custom/nssf.yaml
    depends_on:
      - v-nrf
      - h-scp

  v-bsf:
    container_name: v-bsf
    image: 'bsf:${OPEN5GS_VERSION}'
    build:
      context: ../../images/bsf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/bsf.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.33
        aliases:
          - bsf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-bsf_config
        target: /etc/open5gs/custom/bsf.yaml
    depends_on:
      - v-nrf
      - h-scp

  v-pcf:
    container_name: v-pcf
    image: 'pcf:${OPEN5GS_VERSION}'
    build:
      context: ../../images/pcf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/pcf.yaml'
    restart: unless-stopped
    networks:
      open5gs:
        ipv4_address: 10.33.33.34
        aliases:
          - pcf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-pcf_config
        target: /etc/open5gs/custom/pcf.yaml
    depends_on:
      - v-nrf
      - h-scp

  v-amf:
    container_name: v-amf
    image: 'amf:${OPEN5GS_VERSION}'
    build:
      context: ../../images/amf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/amf.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.35
        aliases:
          - amf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-amf_config
        target: /etc/open5gs/custom/amf.yaml
    depends_on:
      - v-nrf
      - h-scp

  v-smf:
    container_name: v-smf
    image: 'smf:${OPEN5GS_VERSION}'
    build:
      context: ../../images/smf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/smf.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.36
        aliases:
          - smf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-smf_config
        target: /etc/open5gs/custom/smf.yaml
    depends_on:
      - v-nrf
      - v-upf
      - h-scp

  v-upf:
    container_name: v-upf
    image: 'upf:${OPEN5GS_VERSION}'
    build:
      context: ../../images/upf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/upf.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.37
        aliases:
          - upf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-upf_config
        target: /etc/open5gs/custom/upf.yaml
    privileged: true
    cap_add:
      - NET_ADMIN

  v-scp:
    container_name: v-scp
    image: 'scp:${OPEN5GS_VERSION}'
    build:
      context: ../../images/scp
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/custom/scp.yaml'
    networks:
      open5gs:
        ipv4_address: 10.33.33.38
        aliases:
          - scp.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-scp_config
        target: /etc/open5gs/custom/scp.yaml
    cap_add:
      - NET_ADMIN

  v-sepp:
    container_name: v-sepp
    image: 'sepp:${OPEN5GS_VERSION}'
    build:
      context: ../../images/sepp
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: '-c /etc/open5gs/default/sepp.yaml'
    restart: unless-stopped
    networks:
      open5gs:
        ipv4_address: 10.33.33.21
        aliases:
          - sepp.5gc.mnc070.mcc999.3gppnetwork.org
          - sepp2.localdomain
    environment:
      - SEPP_TYPE=sepp2
      - REGENERATE_CERTS=true
      - TLS_DIR=/etc/open5gs/default/tls
      - SEPP_FQDN=sepp2.localdomain
      - SEPP_PLMN_FQDN=sepp.5gc.mnc070.mcc999.3gppnetwork.org
    volumes:
      - sepp_certs:/etc/open5gs/default/tls
      - sepp_ca:/etc/open5gs/default/ca
    configs:
      - source: v-sepp_config
        target: /etc/open5gs/default/sepp.yaml
    ports:
      - '0.0.0.0:8777:7777/tcp' # SBI Server
      - '0.0.0.0:8778:7778/tcp' # N32c Server
      - '0.0.0.0:8779:7779/tcp' # N32f Server
    depends_on:
      - v-nrf
      - h-scp

  packetrusher:
    container_name: packetrusher
    image: 'ghcr.io/borjis131/packetrusher:20250225'
    command: '--config /PacketRusher/config/packetrusher.yaml ue'
    networks:
      open5gs:
        aliases:
          - gnb.packetrusher.org
    configs:
      - source: packetrusher_config
        target: /PacketRusher/config/packetrusher.yaml
    privileged: true
    cap_add:
      - ALL
      - NET_ADMIN
    depends_on:
      - v-amf
      - v-smf
      - v-pcf
      - h-udr
      - h-scp

  webui:
    container_name: webui
    image: 'webui:${OPEN5GS_VERSION}'
    build:
      context: ../../images/webui
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - NODE_VERSION=${NODE_VERSION}
    environment:
      - DB_URI=mongodb://db.open5gs.org/open5gs
      - PORT=9999
      - HOSTNAME=0.0.0.0
      - NODE_ENV=dev
    command: 'run dev'
    networks:
      open5gs:
        aliases:
          - webui.open5gs.org
    depends_on:
      - db
    ports:
      - '0.0.0.0:9999:9999/tcp'

networks:
  open5gs:
    name: open5gs
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-ogs
    ipam:
      config:
        - subnet: 10.33.33.0/24

volumes:
  db_data:
    name: open5gs_db_data
    labels:
      org.open5gs.mongodb_version: ${MONGODB_VERSION}
  db_config:
    name: open5gs_db_config
    labels:
      org.open5gs.mongodb_version: ${MONGODB_VERSION}
  sepp_certs:
    name: open5gs_sepp_certs
  sepp_ca:
    name: open5gs_sepp_ca
  captures:
    name: open5gs_captures

configs:
  h-nrf_config:
    file: ../../configs/roaming/h-nrf.yaml
  h-ausf_config:
    file: ../../configs/roaming/h-ausf.yaml
  h-udm_config:
    file: ../../configs/roaming/h-udm.yaml
  h-udr_config:
    file: ../../configs/roaming/h-udr.yaml
  h-scp_config:
    file: ../../configs/roaming/h-scp.yaml
  h-sepp_config:
    file: ../../configs/roaming/h-sepp.yaml
  v-nrf_config:
    file: ../../configs/roaming/v-nrf.yaml
  v-ausf_config:
    file: ../../configs/roaming/v-ausf.yaml
  v-nssf_config:
    file: ../../configs/roaming/v-nssf.yaml
  v-bsf_config:
    file: ../../configs/roaming/v-bsf.yaml
  v-pcf_config:
    file: ../../configs/roaming/v-pcf.yaml
  v-amf_config:
    file: ../../configs/roaming/v-amf.yaml
  v-smf_config:
    file: ../../configs/roaming/v-smf.yaml
  v-upf_config:
    file: ../../configs/roaming/v-upf.yaml
  v-scp_config:
    file: ../../configs/roaming/v-scp.yaml
  v-sepp_config:
    file: ../../configs/roaming/v-sepp.yaml
  packetrusher_config:
    file: ../../configs/roaming/packetrusher.yaml
