apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: hplmn
  labels:
    app: mongodb
    component: database
    part-of: open5gs
data:
  init-mongo.js: |
    // Initialize Open5GS database
    db = db.getSiblingDB('open5gs');

    // Create collections if they don't exist
    db.createCollection('subscribers');
    db.createCollection('policy_rules');

    // Create indexes for better performance
    db.subscribers.createIndex({ "imsi": 1 }, { unique: true });
    db.subscribers.createIndex({ "msisdn": 1 });

    print('Open5GS database initialized successfully');
