apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: hplmn
  labels:
    app: mongodb
    component: database
    part-of: open5gs
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    app: mongodb
---
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: hplmn
  labels:
    app: mongodb
    component: database
    part-of: open5gs
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    app: mongodb
