apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-config
  namespace: vplmn
data:
  upf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/upf.log

    global:
      max:
        ue: 100000

    upf:
      pfcp:
        server:
          - dev: eth0 
            advertise: upf.5gc.mnc070.mcc999.3gppnetwork.org
        client:
      gtpu:
        server:
          - dev: eth0 
            advertise: upf.5gc.mnc070.mcc999.3gppnetwork.org
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dev: ogstun
      dns:
        - 8.8.8.8
        - 8.8.4.4