apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
  namespace: vplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      initContainers:
        - name: setup-network
          image: alpine:latest
          securityContext:
            privileged: true
            capabilities:
              add: ['NET_ADMIN']
          command:
            - /bin/sh
            - -c
            - |
              # Enable IP forwarding
              echo 1 > /proc/sys/net/ipv4/ip_forward
              # Set up NAT for internet access
              apk add --no-cache iptables
              iptables -t nat -A POSTROUTING -s 10.45.0.0/16 -o eth0 -j MASQUERADE
      containers:
        - name: upf
          image: docker.io/vinch05/upf:v2.7.5
          imagePullPolicy: IfNotPresent
          command: ['open5gs-upfd', '-c', '/etc/open5gs/upf.yaml']
          resources:
            requests:
              cpu: '5m'
              memory: '512Mi'
            limits:
              cpu: '10m'
              memory: '5Gi'
          securityContext:
            privileged: true
            capabilities:
              add: ['NET_ADMIN', 'NET_RAW', 'SYS_ADMIN']
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/upf.yaml
              subPath: upf.yaml
            - name: dev-net-tun
              mountPath: /dev/net/tun
              readOnly: true
            - name: var-log
              mountPath: /var/log/open5gs
          ports:
            - containerPort: 80
              name: sbi
            - containerPort: 8805
              name: pfcp
            - containerPort: 2152
              name: gtp
      volumes:
        - name: config
          configMap:
            name: upf-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: var-log
          emptyDir: {}
