apiVersion: v1
kind: Service
metadata:
  name: upf
  namespace: vplmn
spec:
  selector:
    app: upf
  ports:
    - name: pfcp
      protocol: UDP
      port: 8805
      targetPort: 8805
    - name: gtpu
      protocol: UDP
      port: 2152
      targetPort: 2152