apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-config
  namespace: vplmn
data:
  pcf.yaml: |
    #db_uri: mongodb://mongodb.hplmn.svc.cluster.local/open5gs

    logger:
      file:
        path: /var/log/open5gs/pcf.log
    global:
      max:
        ue: 1024
    pcf:
      sbi:
        server:
          - dev: eth0
            advertise: pcf.5gc.mnc070.mcc999.3gppnetwork.org
        client:
          scp:
            - uri: http://scp.5gc.mnc070.mcc999.3gppnetwork.org
      policy:
        - plmn_id:
            mcc: 001
            mnc: 01
          slice:
            - sst: 1
              sd: 000001
              default_indicator: true
              session:
                - name: internet
                  type: 1
                  ambr:
                    downlink:
                      value: 1
                      unit: 3
                    uplink:
                      value: 1
                      unit: 3
                  qos:
                    index: 9
                    arp:
                      priority_level: 8
                      pre_emption_vulnerability: 1
                      pre_emption_capability: 1
