apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf
  namespace: vplmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcf
  template:
    metadata:
      labels:
        app: pcf
    spec:
      containers:
        - name: pcf
          image: docker.io/library/pcf-local:v2.7.5
          imagePullPolicy: IfNotPresent
          command: [ "open5gs-pcfd", "-c", "/etc/open5gs/pcf.yaml" ]
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/pcf.yaml
              subPath: pcf.yaml
          ports:
            - containerPort: 80
              name: sbi
      volumes:
        - name: config
          configMap:
            name: pcf-config 