apiVersion: v1
kind: ConfigMap
metadata:
  name: bsf-config
  namespace: vplmn
data:
  bsf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/bsf.log

    global:

    bsf:
      sbi:
        server:
          - dev: eth0
            advertise: bsf.5gc.mnc070.mcc999.3gppnetwork.org
        client:
          scp:
            - uri: http://scp.5gc.mnc070.mcc999.3gppnetwork.org